<#
.SYNOPSIS
    Start the local AI stack on Windows.
.DESCRIPTION
    Thin PowerShell wrapper around scripts/start.sh (the canonical
    launcher). Ensures Docker Desktop is running, then invokes the bash
    script via WSL (or falls back to a native docker-compose sequence).

    Since Phase 1, the stack is Docker-native and the LM Studio / lms
    CLI is no longer a dependency; since Phase 6, Tailscale is no
    longer in the launch path (run scripts/setup-cloudflared.sh for
    public access via Cloudflare Tunnel).
.EXAMPLE
    .\scripts\start.ps1
#>
param()

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent

function Write-Step($msg) { Write-Host "`n>> $msg" -ForegroundColor Cyan }
function Write-OK($msg)   { Write-Host "   OK: $msg" -ForegroundColor Green }
function Write-Fail($msg) { Write-Host "   FAIL: $msg" -ForegroundColor Red }

function New-Secret {
    # 48 random bytes → URL-safe base64 (mirrors python secrets.token_urlsafe(48)).
    $bytes = New-Object byte[] 48
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+','-').Replace('/','_')
}

function Initialize-EnvLocal {
    $envPath = Join-Path $root ".env.local"
    if (Test-Path $envPath) {
        $hasKey = Select-String -Path $envPath -Pattern '^AUTH_SECRET_KEY=.+' -Quiet
        if ($hasKey) { return }
    }

    Write-Step ".env.local missing or AUTH_SECRET_KEY not set"
    if (-not [Environment]::UserInteractive) {
        Write-Fail "Non-interactive session — can't prompt. Copy .env.example to .env.local and fill it in (see docs/backend-startup.md)."
        exit 1
    }
    Write-Host "   Initializing .env.local interactively (Ctrl-C to abort)."

    $authKey = New-Secret
    Write-OK "Generated AUTH_SECRET_KEY"

    $ans = Read-Host "   Generate a separate HISTORY_SECRET_KEY (recommended) [Y/n]"
    if ([string]::IsNullOrWhiteSpace($ans) -or $ans -match '^[Yy]') {
        $historyKey = New-Secret
        Write-OK "Generated HISTORY_SECRET_KEY"
    } else {
        $historyKey = ""
    }

    $adminEmails = Read-Host "   Admin email(s) — comma-separated, blank to disable admin UI"
    $publicUrl   = Read-Host "   Public base URL [http://localhost:3000]"
    if ([string]::IsNullOrWhiteSpace($publicUrl)) { $publicUrl = "http://localhost:3000" }
    $cors = Read-Host "   Allowed CORS origins [*]"
    if ([string]::IsNullOrWhiteSpace($cors)) { $cors = "*" }

    $smtpHost = Read-Host "   SMTP host — blank = log magic links to backend stdout"
    $smtpBlock = ""
    if (-not [string]::IsNullOrWhiteSpace($smtpHost)) {
        $smtpPort = Read-Host "   SMTP port [587]"
        if ([string]::IsNullOrWhiteSpace($smtpPort)) { $smtpPort = "587" }
        $smtpUser = Read-Host "   SMTP user"
        $smtpPassSecure = Read-Host "   SMTP pass" -AsSecureString
        $smtpPass = [System.Net.NetworkCredential]::new("", $smtpPassSecure).Password
        $smtpFrom = Read-Host "   From address [noreply@localaistack.local]"
        if ([string]::IsNullOrWhiteSpace($smtpFrom)) { $smtpFrom = "noreply@localaistack.local" }
        $smtpBlock = @"
SMTP_HOST=$smtpHost
SMTP_PORT=$smtpPort
SMTP_USER=$smtpUser
SMTP_PASS=$smtpPass
AUTH_EMAIL_FROM=$smtpFrom
"@
    }

    $now = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $body = @"
# Auto-generated by scripts/start.ps1 on $now.
# Edit by hand to add Cloudflare, Ollama tuning, etc. See .env.example.

AUTH_SECRET_KEY=$authKey
HISTORY_SECRET_KEY=$historyKey
ADMIN_EMAILS=$adminEmails
PUBLIC_BASE_URL=$publicUrl
ALLOWED_ORIGINS=$cors
$smtpBlock
"@
    Set-Content -Path $envPath -Value $body -NoNewline -Encoding UTF8
    Write-OK "Wrote $envPath"
}

Initialize-EnvLocal

# ── Docker Desktop ────────────────────────────────────────────────────────
Write-Step "Checking Docker..."
$dockerReady = $false
for ($i = 0; $i -lt 12; $i++) {
    $out = docker ps 2>&1
    if ($LASTEXITCODE -eq 0) { $dockerReady = $true; break }
    if ($i -eq 0) {
        Write-Host "   Docker not running - starting Docker Desktop..."
        Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe"
    }
    Start-Sleep 5
}
if (-not $dockerReady) { Write-Fail "Docker did not start in time."; exit 1 }
Write-OK "Docker is running"

# ── Compose up ────────────────────────────────────────────────────────────
Write-Step "docker compose up -d"
Set-Location $root
docker compose up -d 2>&1 | ForEach-Object { Write-Host "   $_" -ForegroundColor DarkGray }
if ($LASTEXITCODE -ne 0) { Write-Fail "docker compose up failed"; exit 1 }

# ── Wait for backend ──────────────────────────────────────────────────────
Write-Step "Waiting for backend /healthz..."
for ($i = 0; $i -lt 30; $i++) {
    try {
        $r = Invoke-WebRequest http://localhost:8000/healthz -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        if ($r.StatusCode -eq 200) { Write-OK "Backend is ready"; break }
    } catch {}
    Start-Sleep 2
}

# ── Warm-pull tier models in the background ───────────────────────────────
Write-Step "Pulling tier models (background)"
Start-Process -NoNewWindow -FilePath "bash" -ArgumentList "$root/scripts/setup-models.sh","--skip-vision" -ErrorAction SilentlyContinue
Write-OK "Launched setup-models.sh"

# ── Done ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "=========================================" -ForegroundColor Green
Write-Host "  Stack is ready!" -ForegroundColor Green
Write-Host "  Frontend:  http://localhost:3000" -ForegroundColor Green
Write-Host "  Backend:   http://localhost:8000/healthz" -ForegroundColor Green
Write-Host "  VRAM:      http://localhost:8000/api/vram" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Green
