#!/usr/bin/env bash
# Bring up the local AI stack. Canonical launcher — the .ps1 versions wrap
# this via WSL on Windows.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

cyan()  { printf "\033[36m>> %s\033[0m\n" "$*"; }
green() { printf "\033[32m   OK: %s\033[0m\n" "$*"; }
warn()  { printf "\033[33m   WARN: %s\033[0m\n" "$*"; }
fail()  { printf "\033[31m   FAIL: %s\033[0m\n" "$*" >&2; exit 1; }

# ── Docker ──────────────────────────────────────────────────────────────
cyan "Checking Docker"
if ! docker ps >/dev/null 2>&1; then
  fail "Docker is not running. Start Docker Desktop and re-run."
fi
green "Docker is running"

# ── env file ─────────────────────────────────────────────────────────────
# Compose reads .env.local automatically; we only need to prompt the user
# if it's missing or AUTH_SECRET_KEY is blank (the backend refuses to start
# without it). Non-interactive shells get a clear instruction instead of a
# hang.
ensure_env_local() {
  if [ -f "$ROOT/.env.local" ] && grep -qE '^AUTH_SECRET_KEY=.+' "$ROOT/.env.local"; then
    return 0
  fi

  cyan ".env.local missing or AUTH_SECRET_KEY not set"
  if [ ! -t 0 ]; then
    fail "stdin is not a TTY — can't prompt. Run: cp .env.example .env.local && edit it (see docs/backend-startup.md)."
  fi
  if ! command -v python3 >/dev/null 2>&1; then
    fail "python3 is required to generate auth secrets. Install python3 or create .env.local manually."
  fi

  echo "   Initializing .env.local interactively (Ctrl-C to abort)."

  local auth_key history_key admin_emails public_url cors smtp_host
  local smtp_port smtp_user smtp_pass smtp_from smtp_block=""

  auth_key=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')
  green "Generated AUTH_SECRET_KEY"

  printf "   Generate a separate HISTORY_SECRET_KEY (recommended) [Y/n]? "
  read -r ans
  case "${ans:-Y}" in
    [nN]*) history_key="" ;;
    *)
      history_key=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')
      green "Generated HISTORY_SECRET_KEY"
      ;;
  esac

  printf "   Admin email(s) — comma-separated, blank to disable admin UI: "
  read -r admin_emails

  printf "   Public base URL [http://localhost:3000]: "
  read -r public_url
  public_url="${public_url:-http://localhost:3000}"

  printf "   Allowed CORS origins [*]: "
  read -r cors
  cors="${cors:-*}"

  printf "   SMTP host — blank = log magic links to backend stdout: "
  read -r smtp_host
  if [ -n "$smtp_host" ]; then
    printf "   SMTP port [587]: "
    read -r smtp_port; smtp_port="${smtp_port:-587}"
    printf "   SMTP user: "
    read -r smtp_user
    printf "   SMTP pass: "
    stty -echo 2>/dev/null || true
    read -r smtp_pass
    stty echo 2>/dev/null || true
    echo
    printf "   From address [noreply@localaistack.local]: "
    read -r smtp_from; smtp_from="${smtp_from:-noreply@localaistack.local}"
    smtp_block=$(printf 'SMTP_HOST=%s\nSMTP_PORT=%s\nSMTP_USER=%s\nSMTP_PASS=%s\nAUTH_EMAIL_FROM=%s\n' \
      "$smtp_host" "$smtp_port" "$smtp_user" "$smtp_pass" "$smtp_from")
  fi

  umask 077
  {
    printf '# Auto-generated by scripts/start.sh on %s.\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# Edit by hand to add Cloudflare, Ollama tuning, etc. See .env.example.\n\n'
    printf 'AUTH_SECRET_KEY=%s\n' "$auth_key"
    printf 'HISTORY_SECRET_KEY=%s\n' "$history_key"
    printf 'ADMIN_EMAILS=%s\n' "$admin_emails"
    printf 'PUBLIC_BASE_URL=%s\n' "$public_url"
    printf 'ALLOWED_ORIGINS=%s\n' "$cors"
    [ -n "$smtp_block" ] && printf '%s' "$smtp_block"
  } > "$ROOT/.env.local"
  green "Wrote $ROOT/.env.local (mode 600)"
}

ensure_env_local

cyan "Loading .env.local"
set -a; . "$ROOT/.env.local"; set +a

# ── Compose up ───────────────────────────────────────────────────────────
cyan "docker compose up -d"
docker compose up -d

# ── Wait for backend health ──────────────────────────────────────────────
cyan "Waiting for backend (http://localhost:8000/healthz)"
for i in $(seq 1 30); do
  if curl -fsS --max-time 2 http://localhost:8000/healthz >/dev/null 2>&1; then
    green "Backend is ready"
    break
  fi
  sleep 2
  if [ "$i" = "30" ]; then
    warn "Backend did not come up in 60s — check: docker compose logs backend"
  fi
done

# ── Warm-pull Ollama tier models (non-blocking) ──────────────────────────
if [ "${AUTO_PULL_MODELS:-true}" = "true" ]; then
  cyan "Running setup-models.sh (background)"
  (bash "$ROOT/scripts/setup-models.sh" --skip-vision >/dev/null 2>&1 &)
fi

# ── Done ─────────────────────────────────────────────────────────────────
green "Stack is up"
echo "   Backend:    http://localhost:8000/healthz"
echo "   Open WebUI: http://localhost:3000"
echo "   VRAM stats: http://localhost:8000/api/vram"
