"""
title: Autodesk Fusion 360 — Launch + Script/Add-in Installation
author: local-ai-stack
description: Open Fusion 360 (or a .f3d / .f3z file) and install Python scripts and add-ins into Fusion's standard API folders. Fusion has no headless Python mode, so the workflow is: model writes a Python script using the `adsk` API → tool drops it into `%APPDATA%\\Autodesk\\Autodesk Fusion 360\\API\\Scripts\\<name>\\` (or `AddIns\\<name>\\`) with a matching .manifest → user clicks Run inside Fusion (or Fusion auto-loads the add-in on next launch).
required_open_webui_version: 0.4.0
requirements:
version: 1.0.0
licence: MIT
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent
from typing import Optional

from pydantic import BaseModel, Field


def _default_fusion_exe() -> str:
    candidate = Path.home() / "AppData/Local/Autodesk/webdeploy/production/Fusion360.exe"
    if candidate.exists():
        return str(candidate)
    appdata = Path(os.environ.get("LOCALAPPDATA", str(Path.home() / "AppData/Local")))
    deploy = appdata / "Autodesk" / "webdeploy" / "production"
    if deploy.exists():
        for sub in deploy.iterdir():
            exe = sub / "Fusion360.exe"
            if exe.exists():
                return str(exe)
    return str(candidate)  # Best-guess; user can override.


def _default_api_root() -> str:
    appdata = Path(os.environ.get("APPDATA", str(Path.home() / "AppData/Roaming")))
    return str(appdata / "Autodesk" / "Autodesk Fusion 360" / "API")


# Minimal "Hello world" templates so the model can scaffold quickly.
_SCRIPT_BOILERPLATE = dedent('''\
    import adsk.core, adsk.fusion, traceback

    def run(context):
        ui = None
        try:
            app = adsk.core.Application.get()
            ui = app.userInterface
            # ── Generated body ─────────────────────────────────────────────
            {body}
            # ── End body ───────────────────────────────────────────────────
        except Exception:
            if ui:
                ui.messageBox("Failed:\\n" + traceback.format_exc())
''')


_ADDIN_BOILERPLATE = dedent('''\
    import adsk.core, adsk.fusion, traceback

    handlers = []

    def run(context):
        ui = None
        try:
            app = adsk.core.Application.get()
            ui = app.userInterface
            # ── Add-in start ─────────────────────────────────────────────
            {body}
            # ── End start ────────────────────────────────────────────────
        except Exception:
            if ui:
                ui.messageBox("Add-in failed to start:\\n" + traceback.format_exc())

    def stop(context):
        try:
            handlers.clear()
        except Exception:
            pass
''')


class Tools:
    class Valves(BaseModel):
        FUSION_EXE: str = Field(
            default_factory=_default_fusion_exe,
            description="Path to Fusion360.exe. Auto-detected from %LOCALAPPDATA%/Autodesk/webdeploy/production.",
        )
        API_ROOT: str = Field(
            default_factory=_default_api_root,
            description="Root of the Fusion API folder (Scripts and AddIns subfolders go here).",
        )

    def __init__(self):
        self.valves = self.Valves()

    # ── Helpers ───────────────────────────────────────────────────────────

    def _which(self) -> str:
        exe = self.valves.FUSION_EXE
        if Path(exe).exists():
            return exe
        located = shutil.which(exe) or shutil.which("Fusion360")
        if located:
            return located
        raise FileNotFoundError(f"Fusion 360 binary not found: {exe}")

    def _scripts_dir(self) -> Path:
        return Path(self.valves.API_ROOT).expanduser() / "Scripts"

    def _addins_dir(self) -> Path:
        return Path(self.valves.API_ROOT).expanduser() / "AddIns"

    def _write_manifest(
        self,
        target_dir: Path,
        name: str,
        kind: str,
        autostart: bool = False,
        description: str = "",
    ) -> Path:
        manifest = {
            "autodeskProduct": "Fusion360",
            "type": kind,                 # "script" or "addin"
            "id": f"local-ai-stack.{name}",
            "author": "local-ai-stack",
            "description": {"": description or f"Generated by local-ai-stack ({kind})"},
            "version": "1.0.0",
            "runOnStartup": bool(autostart),
            "supportedOS": "windows|mac",
            "editEnabled": True,
        }
        path = target_dir / f"{name}.manifest"
        path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        return path

    # ── Launch ────────────────────────────────────────────────────────────

    def launch_fusion(self, __user__: Optional[dict] = None) -> str:
        """
        Open Fusion 360. Detached — returns PID immediately.
        :return: Confirmation with PID.
        """
        argv = [self._which()]
        kwargs: dict = {"close_fds": True}
        if sys.platform == "win32":
            kwargs["creationflags"] = 0x00000008 | 0x00000200
        else:
            kwargs["start_new_session"] = True
        proc = subprocess.Popen(argv, **kwargs)
        return f"opened Fusion 360 (pid={proc.pid})"

    def open_file(self, path: str, __user__: Optional[dict] = None) -> str:
        """
        Open a Fusion design file (.f3d or .f3z) in Fusion 360.
        :param path: Absolute path to the design file.
        :return: Confirmation with PID.
        """
        target = Path(path).expanduser().resolve()
        if not target.exists():
            return f"Not found: {target}"
        argv = [self._which(), str(target)]
        kwargs: dict = {"close_fds": True}
        if sys.platform == "win32":
            kwargs["creationflags"] = 0x00000008 | 0x00000200
        else:
            kwargs["start_new_session"] = True
        proc = subprocess.Popen(argv, **kwargs)
        return f"opened in Fusion 360: {target} (pid={proc.pid})"

    # ── Script / Add-in installation ──────────────────────────────────────

    def install_script(
        self,
        name: str,
        body: str = "",
        full_source: str = "",
        description: str = "",
        __user__: Optional[dict] = None,
    ) -> str:
        """
        Install a Fusion 360 Python script under API\\Scripts\\<name>\\. Either
        provide just the `body` (it will be wrapped in a standard `def run(context)`
        template) or pass `full_source` to install verbatim. Once installed the
        script appears under Tools → Scripts and Add-ins → My Scripts in Fusion.
        :param name: Folder/file name (no spaces). Becomes <name>/<name>.py.
        :param body: Script body inserted into the run(context) template.
        :param full_source: Override the template entirely with your own .py.
        :param description: Free-text description shown in Fusion's UI.
        :return: Path it was installed to.
        """
        if not name or any(c in name for c in r' /\:*?"<>|'):
            return f"Invalid name: {name!r}"
        target_dir = self._scripts_dir() / name
        target_dir.mkdir(parents=True, exist_ok=True)
        py = target_dir / f"{name}.py"
        if full_source:
            py.write_text(full_source, encoding="utf-8")
        else:
            py.write_text(
                _SCRIPT_BOILERPLATE.format(body=body or 'pass'),
                encoding="utf-8",
            )
        manifest_path = self._write_manifest(
            target_dir, name, kind="script", description=description,
        )
        return (
            f"installed Fusion 360 script -> {py}\n"
            f"manifest -> {manifest_path}\n"
            "Run it via Tools → Scripts and Add-ins → My Scripts → "
            f"{name} → Run."
        )

    def install_addin(
        self,
        name: str,
        body: str = "",
        full_source: str = "",
        autostart: bool = True,
        description: str = "",
        __user__: Optional[dict] = None,
    ) -> str:
        """
        Install a Fusion 360 add-in under API\\AddIns\\<name>\\. Add-ins differ
        from scripts in that they have explicit start/stop entry points and can
        be set to auto-run on Fusion launch.
        :param name: Folder/file name. Becomes <name>/<name>.py.
        :param body: Code inserted into run(context).
        :param full_source: Override the template entirely.
        :param autostart: When True, manifest sets runOnStartup so the add-in loads with Fusion.
        :param description: Free-text description.
        :return: Path it was installed to.
        """
        if not name or any(c in name for c in r' /\:*?"<>|'):
            return f"Invalid name: {name!r}"
        target_dir = self._addins_dir() / name
        target_dir.mkdir(parents=True, exist_ok=True)
        py = target_dir / f"{name}.py"
        if full_source:
            py.write_text(full_source, encoding="utf-8")
        else:
            py.write_text(
                _ADDIN_BOILERPLATE.format(body=body or 'pass'),
                encoding="utf-8",
            )
        manifest_path = self._write_manifest(
            target_dir, name, kind="addin", autostart=autostart,
            description=description,
        )
        return (
            f"installed Fusion 360 add-in -> {py}\n"
            f"manifest -> {manifest_path}\n"
            f"autostart={autostart}. Restart Fusion to load it."
        )

    def list_scripts(self, __user__: Optional[dict] = None) -> str:
        """
        List installed Fusion 360 scripts (in the user-scoped Scripts folder).
        :return: Newline-delimited list with paths.
        """
        d = self._scripts_dir()
        if not d.exists():
            return f"(no scripts dir yet) {d}"
        rows = [str(p) for p in sorted(d.iterdir()) if p.is_dir()]
        return "\n".join(rows) if rows else "(no installed scripts)"

    def list_addins(self, __user__: Optional[dict] = None) -> str:
        """
        List installed Fusion 360 add-ins (in the user-scoped AddIns folder).
        :return: Newline-delimited list with paths.
        """
        d = self._addins_dir()
        if not d.exists():
            return f"(no addins dir yet) {d}"
        rows = [str(p) for p in sorted(d.iterdir()) if p.is_dir()]
        return "\n".join(rows) if rows else "(no installed add-ins)"

    def remove_script(self, name: str, __user__: Optional[dict] = None) -> str:
        """
        Delete a previously installed script directory.
        :param name: Script name to remove (folder under API/Scripts).
        :return: Confirmation.
        """
        if not name or any(c in name for c in r' /\:*?"<>|'):
            return f"Invalid name: {name!r}"
        target = self._scripts_dir() / name
        if not target.exists():
            return f"Not found: {target}"
        shutil.rmtree(target)
        return f"removed -> {target}"

    def remove_addin(self, name: str, __user__: Optional[dict] = None) -> str:
        """
        Delete a previously installed add-in directory.
        :param name: Add-in name to remove (folder under API/AddIns).
        :return: Confirmation.
        """
        if not name or any(c in name for c in r' /\:*?"<>|'):
            return f"Invalid name: {name!r}"
        target = self._addins_dir() / name
        if not target.exists():
            return f"Not found: {target}"
        shutil.rmtree(target)
        return f"removed -> {target}"
